# Примеры HTTP-запросов автопечати и печати созданных вручную этикеток.
@hostname = 127.0.0.1
@port = 5000
@host = http://{{hostname}}:{{port}}

@printNumber = {{host}}/print-number

###
POST {{printNumber}}
content-type: application/json

{
    "text": "500-1"
}

###
POST {{printNumber}}
content-type: application/json

{
    "text": "КГТ-23"
}

###
POST {{host}}/print-label
content-type: application/json

{
    "contentType": "text",
    "content": "Заказ № 12345",
    "bold": true,
    "underline": false
}
