// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/action/set-theme": {
    params: {};
  };
  "/action/set-theme-style": {
    params: {};
  };
  "/action/set-config": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/settings" | "/action/set-theme" | "/action/set-theme-style" | "/action/set-config";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/action.set-theme.tsx": {
    id: "routes/action.set-theme";
    page: "/action/set-theme";
  };
  "routes/action.set-theme-style.tsx": {
    id: "routes/action.set-theme-style";
    page: "/action/set-theme-style";
  };
  "routes/action.set-config.tsx": {
    id: "routes/action.set-config";
    page: "/action/set-config";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/action.set-theme": typeof import("./app/routes/action.set-theme.tsx");
  "routes/action.set-theme-style": typeof import("./app/routes/action.set-theme-style.tsx");
  "routes/action.set-config": typeof import("./app/routes/action.set-config.tsx");
};